### ISSUE TITLE
Problem with sysctl config

### ISSUE THREAD

**Issue by Duksara** [dpanic/patchfiles#5]
It seems that my network card has problems with busy pool, when i set that up my network goes offline after a few minutes.

Network card in question : RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller

**Comment by dpanic** [comment]
Thank you for reporting, I will investigate this.

**Comment by dpanic** [comment]
I have identified problem.
Problem is in https://github.com/dpanic/patchfiles/blob/main/patches/initial_window_1.yaml and sysctl.conf in combination.

I have decided to remove intial_window
